# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "HOME"
  url = "#about"
  weight = 10



# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 20

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 30

[[main]]
  name = "EXPERIENCE"
  url = "#experience"
   weight = 30

[[main]]
  name = "PUBLICATIONS"
  url = "publication/"
   weight = 40

[[main]]
  parent = "PUBLICATIONS"
  name = "FEATURED"
  url = "publication/#Featured"
  weight = 10

[[main]]
  parent = "PUBLICATIONS"
  name = "ALL"
  url = "publication/#List"
  weight = 20

#[[main]]
#  name = "PROJECTS"
#  url = "projects/"
#  weight = 50

# [[main]]
#    name = "Post"
#    url = "post/"
#    weight = 60

# [[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# [[main]]
#   name = "dropdown"
#   url = "#"
#   hasChildren = true

# [[main]]
#   parent = "dropdown"
#   name = "dropdown 1"
#   url = "#"

# # [[main]]
#   parent = "dropdown"
#   name = "dropdown 2"
#   url = "#!"


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "RESUME/CV"
  url = "files/CV_yunchen.pdf"
  weight = 70


